# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16h9NdsKnMzrCbRqGtX1hRo0PW8gedCit
"""

#Day 3 Assignment:

#From a dictionary, print the Key whose Value is maximum in the dictionary.

S= {'a': 3 ,'b':16, 'c':7, 'd': 20, 'e': 28}
Keymax= max(zip( S.values(), S.keys()))[1]
print(Keymax)